panel:
  title: "Tickets"
  description: "Click al botÃ³n de abajo para crear un ticket privado con el staff."
  color: 9566865
buttons:
  open:
    label: "Click para abrir ticket"
    emoji: "ðŸ“©"
    color: 1
  close:
    label: "Cerrar"
    emoji: "ðŸ”’"
    color: 4
  callStaff:
    label: "Completado"
    emoji: "âœ…"
    color: 3
  close_confirm_yes:
    label: "Si"
    emoji: "âœ”"
    color: 3
  close_confirm_no:
    label: "No"
    emoji: "âŒ"
    color: 4
  delete:
    label: "Cerrar definitivamente"
    emoji: "ðŸ—‘"
    color: 4

channelName: "%emoji%â”ƒ%user%-%category%"
log_channel: "1016023164754608188"

menu:
  placeholder: "Click para seleccionar categorÃ­a"
  options:
    a:
      enabled: true
      label: "FAQ"
      shortName: "faq"
      emoji: "â”"
      description: "Para resolver tus dudas respecto al servidor."
      rise_roles:
        - "1"
      embed:
        title: "Bienvenido a tu ticket"
        description: "Comenta tu problema"
    b:
      enabled: true
      label: "Reportes"
      shortName: "reportes"
      emoji: "ðŸš«"
      description: "DescripciÃ³n."
      rise_roles:
        - "1"
      embed:
        title: "Bienvenido a tu ticket"
        description: "Comenta tu problema"
    c:
      enabled: true
      label: "Regalos"
      shortName: "regalos"
      emoji: "ðŸŽ"
      description: "DescripciÃ³n."
      rise_roles:
        - "1"
      embed:
        title: "Bienvenido a tu ticket"
        description: "Comenta tu problema"
    d:
      enabled: true
      label: "Negocios"
      shortName: "negocios"
      emoji: "ðŸ‘œ"
      description: "DescripciÃ³n.."
      rise_roles:
        - "1"
      embed:
        title: "Bienvenido a tu ticket"
        description: "Comenta tu problema"
    e:
      enabled: true
      label: "Social"
      shortName: "social"
      emoji: "ðŸŒ"
      description: "DescripciÃ³n.."
      rise_roles:
        - "1"
      embed:
        title: "Bienvenido a tu ticket"
        description: "Comenta tu problema"
    f:
      enabled: true
      label: "Postulaciones staff"
      shortName: "staff"
      emoji: "ðŸ”“"
      description: "DescripciÃ³n..."
      rise_roles:
        - "1"
      embed:
        title: "Bienvenido a tu ticket"
        description: "Comenta tu problema"
    g:
      enabled: true
      label: "Postulaciones Dev"
      shortName: "dev"
      emoji: "ðŸ’»"
      description: "DescripciÃ³n..."
      rise_roles:
        - "1"
      embed:
        title: "Bienvenido a tu ticket"
        description: "Comenta tu problema"
    

antispam:
  max_tickets_per_user: 1

staffRol: "660260944882040853"
parentId: "998732499976990840"

messages:

  selectCategory:
    description: "Selecciona una categorÃ­a del menÃº desplegable:"

  ticketContent: "%user%, bienvenido a tu ticket."
  ticketEmbed:
    title: "Bienvenido a tu ticket"
    description: "Comenta tu problema."
  ticketCreated:
    description: "Tu ticket ha sido creado -> %canal%"
  max_tickets:
    description: "No puedes crear mas tickets "
  already_called_staff:
    description: "Ya has llamado al staff."
  callStaff:
    description: "%rol%. Has llamado al staff satisfactoriamente."
    color: 1848641
  already_closed:
    description: "El ticket ya estÃ¡ cerrado."
    color: 7485456
  ticketClose:
    description: "Â¿Seguro que quieres cerrar el ticket?"
    color: 7485456
  ticketClosedConfirmed:
    description: "El ticket ha sido cerrado."
    color: 4589456
  clickToDelete:
    description: "Para borrarlo pulsa en `Cerrar ticket`"
    color: 4854584
  userTranscript:
    title: "Soporte"
    description: "Tu ticket ha sido cerrado"
    fields:
      - name: "Canal"
        value: "%canal%"
        inline: true
      - name: "Cerrado por"
        value: "%staff%"
        inline: true
  staffTranscript:
    title: "Soporte"
    description: "Tu ticket ha sido cerrado"
    fields:
      - name: "Canal"
        value: "%canal%"
        inline: true
      - name: "Cerrado por"
        value: "%staff%"
        inline: true
